export const styles = {
  textinput: {
    backgroundColor: 'white',
    borderRadius: 10,
    marginLeft: 20,
    height: 50,
    borderWidth: 1,
    borderColor: '#00BCD4',
  },
  CircleShapeView: {
    width: 50,
    height: 50,
    borderRadius: 120 / 2,
    backgroundColor: '#00BCD4',
    justifyContent: 'center',
  },
  overlay: {
    flex: 1,
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    //  backgroundColor: 'rgba(0,0,0,0.2)',
    marginLeft: 140,
    marginRight: 100,
    marginTop: 70,
    marginBottom: 350,
  },
  labeltext: {
    marginBottom: 10,
    fontSize: 20,
    marginTop: 10,
    marginLeft: 15,
    // marginLeft:20
  },
  refreshstyle: {
    paddingHorizontal: 30,
    alignSelf: 'flex-end',
    marginRight: 10,
  },
  image: {
    width: 25,
    height: 24,
    alignSelf: 'center',
  },
  updatebuttonstyle: {
    borderRadius: 10,
    marginTop: 20,
    marginBottom: 20,
    marginLeft: 40,
    marginRight: 40,
    backgroundColor: '#089bab',
  },
  textinputstyle: {
    width: 60,
  },
  scrollviewstyle: { marginTop: 10, marginRight: 20 },
  viewPersonalProfileTabsContainer: {
    flex: 0.4,
    flexDirection: 'row',
    justifyContent: 'space-between',
    zIndex: 999,
    top: -30,
  },
  viewPersonalProfileTabs: {
    flex: 0.4,
    //marginLeft: 20,
    borderRadius: 25,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderColor: '#d4d4d4',
    backgroundColor: '#ffffff',
  },
  viewTabs: {
    flex: 1,
    borderRadius: 25,
    borderWidth: 1,
    borderColor: '#ffffff',
    alignItems: 'center',
  },
  viewBusinessTab: {
    borderLeftWidth: 1,
  },
};