import {
  CommonStyles,
  GilRoyMediumColor,
  GilRoyRegularColor,
} from '../shared/Constants';
export const styles = {
  viewContactContainer: {
    flex: 1,
    marginTop: 8,
    backgroundColor: '#f4f6f9',
  },
  viewContact: {
    flex: 1,
    alignSelf: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
    marginBottom: 8,
    borderBottomStartRadius: 25,
    borderBottomEndRadius: 25,
  },
  viewContactDetails: {
    flex: 3,
    marginRight: 10,
  },
  textName_fileName: {
    color: GilRoyMediumColor.fontColor,
    //fontSize: 15,
    paddingBottom: 5,
  },
  viewFabContainer: {
    flex: 1,
    alignItems: 'center',
    paddingBottom: 5,
  },
  numberOfContactsText: {
    fontSize: 18,
    color: '#000',
    marginLeft: 15,
    marginBottom: 10,
  },
  touchableOpacity_Processing: {
    borderWidth: 0.5,
    borderRadius: 15,
    backgroundColor: CommonStyles.appColor,
    borderColor: '#e0e0e0',
  },
  textName_Processing: {
    color: '#a9a9a9',
    textAlign: 'center',
    paddingBottom: 5,
    paddingTop: 5,
  },
  textName_Invite: {
    color: '#ffffff',
    textAlign: 'center',
    paddingBottom: 5,
    paddingTop: 5,
  },
  textName_date: {
    color: GilRoyRegularColor.fontColor,
    fontSize: 13,
    paddingBottom: 5,
  },
  CircleView: {
    flex: 1,
    position: 'absolute',
    bottom: -5,
    right: 2,
    backgroundColor: '#ffffff',
    borderRadius: 50,
    width: 20,
    height: 20,
    alignItems: 'center',
    alignSelf: 'center',
  },
  Tabs: {
    flex: 0.5,
    backgroundColor: '#ffff',
    alignItems: 'center',
    borderColor: '#bdbdbd',
    borderWidth: 0.8,
    borderRadius: 50,
    flexDirection: 'column',
    height: 50,
    marginTop: 35,
    marginLeft: -20,
    width: 50,
  },
};
