import { Dimensions, Platform } from 'react-native';
import {
  CommonStyles,
  GilRoyRegularColor,
  GilRoyMediumColor,
} from '../shared/Constants';

export const styles = {
  button: {
    width: Dimensions.get('window').width - 20,
    height: 70,
    position: 'relative',
    alignSelf: 'center',
    borderRadius: 30,
    marginTop: 10,
    // borderWidth: 1,
  },
  buttonText: {
    color: GilRoyMediumColor.fontColor,
    fontSize: 16,
    //fontWeight: 'bold',
    textAlign: 'center',
    alignSelf: 'center',
  },
  list: {
    paddingVertical: 2,
    margin: 3,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    borderRadius: 30,
  },
  selected: { backgroundColor: 'green' },
  header: {
    justifyContent: 'center',
    alignItems: 'flex-end',
    width: Dimensions.get('window').width - 150,
    height: 66,
    marginBottom: 10,
    backgroundColor: 'white',
  },
  invitationimages: {
    //flex: 0.8,
    // flexDirection: 'column',
    height: 50,
    width: 50,
    borderRadius: 100

    // position: 'absolute',
    // justifyContent: 'center',
    // alignItems: 'center',
    //alignSelf: 'center',
  },
  fab: {
    //flex: 0.8,
    //flexDirection: 'column',
    height: 80,
    width: 80,
    borderRadius: 180,
    position: 'absolute',
    //marginTop: 10,
    //justifyContent: 'center',
    //alignItems: 'center',
    //alignSelf: 'center',
    // backgroundColor: '#ffffff',
    // borderWidth: 1,
    // borderColor: 'black',
    // marginBottom: 2,
  },
  InviteStyle: {
    flex: 1,
    height: 50,
    width: 50,
    borderRadius: 100,
    backgroundColor: CommonStyles.appColor,
    flexDirection: 'column',
    // marginBottom: 2,
  },
  Inviationsfab: {
    flex: 1,
  },
  Ibutton: {
    //alignItems: 'center',
    //backgroundColor: CommonStyles.appColor,
    // color: 'red',
    //marginLeft: 18,
    position: 'absolute',
    top: 10,
    left: 15,
    borderRadius: 50,
    flex: 1,
  },
  iconClose: {
    color: '#ffffff',
    fontSize: 20
  },
  iconMessage: {
    //color: CommonStyles.appColor,
    color: '#ffffff',
    fontSize: 20
  },
  container: {
    flex: 1,
    paddingHorizontal: 10,
    justifyContent: 'center',
    paddingTop: Platform.OS === 'ios' ? 20 : 20,
  },

  text: {
    fontSize: 17,
    color: 'black',
    padding: 10,
  },

  btnText: {
    textAlign: 'center',
    color: 'white',
    fontSize: 20,
  },

  btnTextHolder: {
    borderWidth: 1,
    borderColor: CommonStyles.appColor,
  },

  Btn: {
    padding: 10,
    backgroundColor: CommonStyles.appColor,
  },

  manageInvitationText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#000',
  },
  manageInvitationView: {
    flexDirection: 'row',
    //backgroundColor: '#029fae',
  },
  peopleText: {
    fontSize: 16,
    color: GilRoyMediumColor.fontColor,
  },
  invitationView: {
    flex: 1,
    borderColor: '#e0e0e0',
    borderBottomWidth: 1,
    marginBottom: 8,
    //marginBottom: 5,
    flexDirection: 'row',
    // marginLeft: 10,
    // marginRight: 10,
  },
  firstNameText: {
    height: 50,
    width: 50,
    borderRadius: 100,
    backgroundColor: CommonStyles.appColor,
    // marginBottom: 5,
    justifyContent: 'center',
    // alignItems: 'center',
    // alignSelf: 'center',
    // paddingTop: 10,
  },
  viewMenu: { flex: 0.15, marginLeft: 10 },
  customMenu: {
    marginRight: 5,
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  textMenu: {
    color: 'red',
  },
  SectionStyle: {
    flex: 0.8,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
    borderBottomLeftRadius: 40,
    borderBottomRightRadius: 40,
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
  },
  iconSearch: { fontSize: 16, color: '#a9a9a9', left: 5 },
  TextInputStyleClass: {
    flex: 2,
    //height: 18,
    underlineColor: 'transparent',
    //paddingRight: 90,
  },
  leftHeader: {
    flexDirection: 'column',
    height: 38,
    width: 38,
    borderRadius: 80,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: '#ffffff',
  },

  dbList: {
    borderColor: '#e0e0e0',
    width: Dimensions.get('window').width / 2,
    height: 220,
    borderBottomWidth: 1,
    borderRightWidth: 1,
    //borderRadius: 10,
    paddingLeft: 10,
    paddingRight: 10,
    justifyContent: "space-around"
  },
  iconViewStyle: {
    // flex: 1,
    height: 25,
    width: 25,
    borderRadius: 50,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: '#ffffff',
    borderColor: CommonStyles.appColor,
    borderWidth: 2,
  },
  iconStyle: {
    color: CommonStyles.appColor,
    fontSize: 16,
  },
  invitationTextView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: 10,

  },
  userName: {
    color: GilRoyMediumColor.fontColor,
    fontSize: 18,
  },
  profileCircleView: {
    flexDirection: 'row',
    flex: 0.55,
    alignSelf: 'center',
    position: 'relative',
  },
  nameTitleView: {
    flex: 0.25,
    flexDirection: 'column',
    //margin: 70,
    //width: Dimensions.get('window').width / 2.4,
    alignSelf: 'center',
  },
  touchableMessage: {
    height: 23,
    width: 23,
    //position: 'absolute',
    //flex: 0.2,
    //backgroundColor: '#ffffff',
    backgroundColor: CommonStyles.appColor,
    //paddingVertical: 5,
    borderRadius: 35,
    right: 40,
    bottom: 25,
    //alignItems: 'center',
    //marginLeft: 0,
    //bottom:20
    //marginRight: 50,
  },
  touchablePlus: {
    height: 23,
    width: 23,
    //position: 'absolute',
    //flex: 0.2,
    //backgroundColor: '#ffffff',
    backgroundColor: CommonStyles.appColor,
    //paddingVertical: 5,
    borderRadius: 35,
    //alignItems: 'center',
    marginLeft: 85,
    bottom: 48
    //top:10
    //marginRight: 50,
  },
  icnScanner: { color: '#a9a9a9', fontSize: 16, top: 7 },
  toolScanner: { color: '#a9a9a9', fontSize: 16 },
  viewScanner: {
    flex: 0.3,
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    //marginTop: 5,
    //marginRight: 10,
    right: Platform.OS == 'android' ? 10 : 20,
  },
  DialogButton: {
    borderRadius: 20,
    width: 20,
    borderColor: '#fff',
    height: 10,
    margin: 10,
    borderWidth: 1,
    backgroundColor: CommonStyles.appColor,
  },
  DialogButtonText: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
  },
  SelectedListStyle: {
    marginRight: 8,
    borderBottomColor: 'lightgray',
  },
  SelectedPeopleView: {
    // flex:1,
    height: 60,
    width: 70,
    marginLeft: 15,
    flexDirection: 'column',
    backgroundColor: 'transparent',
  },
  DummyProfileStyle: {
    //flex: 1,
    //flexDirection: 'column',
    height: 55,
    width: 55,
    borderRadius: 110,
    justifyContent: 'center',
    // backgroundColor: CommonStyles.appColor,
    // marginBottom: 2,
  },
  selectedlistcustomrow: {
    //flex: 1,
    flexDirection: 'column',
    //height: 60,
  },
  container1: {
    flex: 2,
    flexDirection: 'row',
    justifyContent: 'space-between',
    // padding: 10,
    borderRadius: 4,
    borderColor: 'red',
    borderWidth: 1,
  },
  listItem: {
    maxWidth: Dimensions.get('window').width / 2,
    flex: 1,
    backgroundColor: '#fff',
    borderRadius: 4,
    borderColor: 'red',
  },
  headerViewMenu: { flex: 1, marginLeft: 20 },
  headerCustomMenu: {
    marginRight: 5,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    borderRadius: 100,
  },
  headerTextMenu: {
    color: 'red',
  },
  headerCenterView: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: 'white',
    borderBottomLeftRadius: 40,
    borderBottomRightRadius: 40,
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    width: Dimensions.get('window').width * 0.56,
  },
  viewContact: {
    flex: 1,
    flexDirection: 'row',
    margin: 10,
  },
  cardsWrapper: {
    //flex: 1,
    marginTop: 5,
    width: '95%',
    alignSelf: 'center',
  },
  card: {
    height: 110,
    marginVertical: 2,
    flexDirection: 'row',
    shadowColor: '#999',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.8,
    shadowRadius: 2,
    elevation: 5,
    borderRadius: 8,
  },
  cardImgWrapper: {
    flex: 1,
  },
  cardImg: {
    height: '100%',
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    borderRadius: 8,
    borderBottomRightRadius: 0,
    borderTopRightRadius: 0,
    borderBottomLeftRadius: 8,
    borderTopLeftRadius: 8,
    overflow: "hidden"
  },
  cardImgBg: {
    height: '100%',
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    borderRadius: 8,
    borderBottomRightRadius: 0,
    borderTopRightRadius: 0,
    borderBottomLeftRadius: 8,
    borderTopLeftRadius: 8,
    overflow: "hidden"
  },
  cardInfo: {
    flex: 2,
    padding: 6,
    borderColor: '#ccc',
    borderWidth: 1,
    borderLeftWidth: 0,
    borderBottomRightRadius: 8,
    borderTopRightRadius: 8,
    backgroundColor: '#fff',
  },
  cardTitle: {
    fontWeight: 'bold',
  },
  cardDetails: {
    fontSize: 12,
    color: '#444',
  },
  profileImage: {
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "center",
    paddingTop: 105,
  },
};
