export const styles = {
  MainContainer: {flex: 5},
  flipped: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#E7F9FB',
    alignSelf: 'flex-start',
  },
  EditoptionView: {
    flex: 0.3,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20,
  },
  EditoptionViewV: {justifyContent: 'space-between', marginTop: 20},
  EditTextView: {
    backgroundColor: 'white',
    borderRadius: 10,
    width: 300,
    marginBottom: 10,
    height: 45,
  },
  EditTextinput: {
    backgroundColor: 'white',
    borderRadius: 10,
    width: 300,
    marginBottom: 10,
    height: 45,
    borderWidth: 1,
  },
  ColorWheelView: {flex: 1, flexDirection: 'row'},
  Colorthumbstyle: {height: 20, width: 20, borderRadius: 25},
  SliderViewstyle: {
    flexDirection: 'row',
    margin: 10,
    borderWidth: 1,
    borderColor:"#fff",
    borderRadius:10,
    backgroundColor:"#fff",
    height:30, top:200, padding:10

  },
  sliderstyle: {paddingHorizontal: 120},
  ModalInsideView: {paddingHorizontal: 60, paddingVertical: 15, margin: 10},
  FontstyleModalTextView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 50,
    paddingVertical: 20,
    borderRadius: 10,
    borderWidth: 1,
  },
  FontStylesTochableView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20,
    paddingLeft: 20,
    paddingRight: 20,
  },
  ShowBottomStylesMainView: {
    flex: 0.5,
    flexDirection: 'row',
    justifyContent: 'space-between',
    // marginTop: 10,
    backgroundColor: '#ffffff',
    borderColor: '#e0e0e0',
  },
  leftHeader: {
    borderColor: '#e0e0e0',
    borderWidth: 1,
    flexDirection: 'column',
    height: 38,
    width: 38,
    borderRadius: 80,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    // right: 8,
    // backgroundColor: '#ffffff',
  },
  headerCustomMenu: {
    marginRight: 5,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    borderRadius: 100,
  },
  headerTextMenu: {
    color: 'red',
  },
};
