import {CommonStyles, GilRoyMediumColor} from '../shared/Constants';
import {PixelRatio} from 'react-native';
export const styles = {
  viewContactContainer: {
    flex: 1,
    marginLeft: 8,
    marginRight: 8,
    marginBottom: 5,
    paddingBottom: 5,
    borderBottomWidth: 0.2,
    borderBottomColor: 'lightgray',
  },
  BgIconStyle: {
    flexDirection: 'column',
    height: 38,
    width: 38,
    borderRadius: 78,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: '#ffffff',
  },
  ReceivedIconStyle: {
    flexDirection: 'column',
    height: 38,
    width: 38,
    borderRadius: 78,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
  },
  TextStyle: {
    marginLeft: 10,
    fontSize: 16,
    color: 'gray',
  },
  viewContact: {
    flex: 1,
    alignSelf: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    //  marginBottom: 10,
  },
  touchableOpacityView_InviteUser: {
    flex: 0.8,
    // backgroundColor: '#089bab',
    alignItems: 'center',
    borderRadius: 50,
    paddingVertical: 8,
    paddingHorizontal: 16,
  },
 
  defaultprofilestyle: {
    flex: 1,
    flexDirection: 'row',
    height: 65,
    width: 65,
    borderRadius: 160,
    // position: 'absolute',
    // marginTop: 10,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: '#ffffff',
    // marginBottom: 2,
  },
  AttendeeContactStyle: {
    flexDirection: 'column',
    marginLeft: 7,
  },
  textName: {
    color: GilRoyMediumColor.fontColor,
    fontSize: 16,
    //alignSelf:'center',
  },
  SendInviteStyle: {
    marginTop: 20,
    alignItems: 'center',
    // borderRadius: 60,
    // paddingVertical: 5,
  },
  name: {
    fontSize: 18,
    color: '#ffffff',
    height: 50,
    width: 50,
    borderRadius: 100,
    backgroundColor: CommonStyles.appColor,
    textAlign: 'center',
    paddingTop: 10,
  },
  MeetingSchedulestyle: {
    borderBottomColor: 'lightgray',
    borderBottomWidth: 1,
    height: 2,
  },
  MeetingDayStyle: {
    flex: 1,
    flexDirection: 'column',
    height: 30,
    width: 70,
    marginRight: 20,
    alignItems: 'center',
    backgroundColor: '#ceebeb',
    borderRadius:30,
    textAlign:'center',
    justifyContent:'center'
  },
  underLine: {
    borderBottomColor: '#A9A9A9',
    borderBottomWidth: 1,
    height: 2,
  },
  Tickmark: {
    top: 10,
    right: 0,
    borderRadius: 50,
    backgroundColor: '#ffffff',
    position:"absolute"
  },
  fab: {
    flexDirection: 'column',
    height: 55,
    width: 55,
    borderRadius: 110,
    justifyContent: 'center',
    backgroundColor: CommonStyles.appColor,
  },
  headerprofile: {
    height: 60,
    width: 60,
    borderRadius: 120,
    justifyContent: 'center',
    backgroundColor: CommonStyles.appColor,
  },
  DialogTextinputStyle: {
    flex: 1,
    borderColor: '#a9a9a9',
    borderBottomWidth: 1,
    marginTop: 20,
    fontSize: 18,
  },
  DialogButtonText: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
  },
  DialogButton: {
    borderRadius: 20,
    width: 20,
    borderColor: '#fff',
    height: 10,
    margin: 10,
    borderWidth: 1,
    backgroundColor: CommonStyles.appColor,
  },
  MeetinginviTIstyle: {
    marginLeft: 10,
    fontSize: 16,
    borderBottomWidth: 0.2,
    borderColor: 'gray',
    color:"#000"
  },
  MeetinginviTIstyle2: {
    marginLeft: 10,
    fontSize: 16,
    // borderBottomWidth: 0.2,
    // borderColor: 'gray',
    color:"#000"
  },
  MeetingLinkstyle: {
    marginLeft: 10,
    fontSize: 16,
    borderBottomWidth: 0.2,
    borderColor: 'gray',
    color:"#32a0db"
  },
  ADTBTNStyles: {
    padding: 7,
    backgroundColor: CommonStyles.appColor,
    borderRadius: 80,
  },
  CompanyAddressTextInputContainer: {
    height: 50,
    borderBottomColor: 'gray',
    borderBottomWidth: 1,
    borderTopWidth: 0,
    backgroundColor: '#f5f6fa',
  },
  CompanyAddressTextInput: {
   // backgroundColor: '#ffffff',
  },
  CompanyAddressTextInputDescription: {
    fontWeight:"bold",
    backgroundColor:"#f5f6fa",
    marginVertical:10,
    borderBottomColor:"gray",
    borderBottomWidth:0.2
  },
  MSGInputstyle: {
    flex: 1,
    borderColor: '#e0e0e0',
    borderWidth: 1,
    margin: 10,
  },
  statustyle: {
    backgroundColor: CommonStyles.appColor,
    paddingVertical: 5,
    borderRadius: 35,
    alignItems: 'center',
    marginBottom: 12,
    marginLeft: 20,
    marginRight: 20,
    width: 80,
  },
  BgIconStyle: {
    flexDirection: 'column',
    height: 38,
    width: 38,
    borderRadius: 78,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: '#ffffff',
  },
};
