import {Dimensions} from 'react-native';
export const grpstyles = {
  CircleView: {
    flex: 1,
    position: 'absolute',
    bottom: -5,
    right: 2,
    backgroundColor: '#ffffff',
    borderRadius: 50,
    width: 20,
    height: 20,
    alignItems: 'center',
    alignSelf: 'center',
  },
  floatingViewAll: {
    position: 'absolute',
    right: 5,
    //top: -50,
    backgroundColor: '#ffff',
    alignItems: 'center',
    borderColor: '#bdbdbd',
    borderWidth: 0.8,
    borderRadius: 30,
    zIndex: 999,
    flexDirection: 'column',
    height: 150,
    width: 30,
    marginTop: 150,
    marginRight: 10,
  },
  DeleteView: {
    backgroundColor: '#ffff',
    alignItems: 'center',
    borderColor: '#bdbdbd',
    borderWidth: 0.8,
    borderRadius: 70,
    position: 'absolute',
    right: 5,
    top: -50,
    width: 25,
    flexDirection: 'column',
    height: 60,
    marginTop: 80,
    marginRight: 20,
  },
  GrpSearchStyle: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: 'white',
    borderBottomLeftRadius: 40,
    borderBottomRightRadius: 40,
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    width: Dimensions.get('window').width * 0.56,
  },
};
