export const SET_AUTH_STATE = 'SET_AUTH_STATE';
export const SET_USER_PROFILE = 'SET_USER_PROFILE';
export const CLEAR_USER_PROFILE = 'CLEAR_USER_PROFILE';
export const SET_BUSINESS_CARD_DETAILS = 'SET_BUSINESS_CARD_DETAILS';
export const CLEAR_BUSINESS_CARD_DETAILS = 'CLEAR_BUSINESS_CARD_DETAILS';
export const SET_MY_CONNECTION_DETAILS = 'SET_MY_CONNECTION_DETAILS';
export const CLEAR_MY_CONNECTION_DETAILS = 'CLEAR_MY_CONNECTION_DETAILS';
