export const Scenes = {
  registration: 'registration',
  contact: 'contact',
  login: 'login',
  card: 'card',
  splashScreen: 'splashScreen',
  startPage: 'startPage',
  homeScreen: 'homeScreen',
  viewCard: 'viewCard',
  nearByProfiles: 'nearByProfiles',
  myConnections: 'myConnections',
  profile: 'profile',
  profileBusiness: 'profileBusiness',
  referAfriend: 'referAfriend',
  referAfriendList: 'referAfriendList',
  settings: 'settings',
  profileCard: 'profileCard',
  profiles: 'profiles',
  myProfile: 'myProfile',
  businessCard: 'businessCard',
  login1: 'login1',
  otp: 'otp',
  verifiedView: 'verifiedView',
  personalDetails: 'personalDetails',
  companyDetails: 'companyDetails',
  selectBusinessCard: 'selectBusinessCard',
  homePage: 'homePage',
  aboutNobHub: 'aboutNobHub',
  changeNumber: 'changeNumber',
  help: 'help',
  groups: 'groups',
  groupsAdd: 'groupsAdd',
  connectedPeople: 'connectedPeople',
  imageView: 'imageView',
  Chats: 'Chats',
  chattingUI: 'chattingUI',
  flagsList: 'flagsList',
  Language:'Language',
  manageInvitations: 'manageInvitations',
  commonHeader: 'commonHeader',
  phoneContacts: 'phoneContacts',
  NearbyProfilesMap: 'NearbyProfilesMap',
  Meetings: 'Meetings',
  ScheduleMetting: 'ScheduleMetting',
  MeetingUsers: 'MeetingUsers',
  MeetingLocation:'MeetingLocation',
  notifications: 'notifications',
  notificationDetails: 'notificationDetails',
  chooseBusinessCard: 'chooseBusinessCard',
  cardCategories: 'cardCategories',
  ChatContacts: 'ChatContacts',
  GroupChatting: 'GroupChatting',
  GroupChatContacts: 'GroupChatContacts',
  groupMembers: 'groupMembers',
  businessShoutOut: 'businessShoutOut',
  postShoutOut: 'postShoutOut',
  ChatGroups: 'ChatGroups',
  scannedCards: 'scannedCards',
  scannedImages: 'scannedImages',
  SelectedPhotos: 'SelectedPhotos',
  categories: 'categories',
  MeetingInvitations: 'MeetingInvitations',
  nearByProfilesPage: 'nearByProfilesPage',
  mapView: 'mapView',
  manageShoutout: 'manageShoutout',
  editShoutout: 'editShoutout',
  helpCenter: 'helpCenter',
  ContactUs: 'ContactUs',
  qrCode: 'qrCode',
  rateUs: 'rateUs',
  features: 'features',
  support: 'support',
  premierMembership: 'premierMembership',
  shareBusinessCard: 'shareBusinessCard',
  termsAndCondtitions: 'termsAndCondtitions',
  privacyPolicy: 'privacyPolicy',
  openImage: 'openImage',
  DeleteAccount: 'DeleteAccount',
};
export const CommonStyles = {
  appColor: '#27BECF',
};
export const GilRoyMediumColor = {
  fontColor: '#1f1f1f',
};
export const GilRoyRegularColor = {
  fontColor: '#777777',
};
export const LightGrayColor = {
  fontColor: '#D3D3D3',
};
export const cardElementGroupIds = {
  FirstName: 1,
  LastName: 112,
  Email: 2,
  HomePhone: 25,
  Address: 4,
  Facebook: 17,
  Skype: 19,
  Linkedin: 18,
  Twitter: 20,
  ComapanyName: 5,
  CompanyAdrees: 10,
  Department: 7,
  CompanyWebsite: 9,
  Extension: 12,
  Fax: 13,
  Title: 6,
  CompanyEmail: 8,
  Mobile: 3,
  Website: 9,
  CompanyMobile: 11,
  Profession: 15,
};

export const PlayStoreLink = {
  android: 'https://play.google.com/store/apps/details?id=com.nobhub.app',
  ios: 'https://play.google.com/store/apps/details?id=com.nobhub.app',
};
export const MyConnection = {
  inviteFriend: 'inviteFriendMessage',
};

export const ImageTypes = {
  profilePicture: 1,
  profileCoverPicture: 2,
  businessLogo: 3,
  businessCoverPicture: 4,
  GroupProfile: 5,
};
