import {Dimensions, Platform} from 'react-native';
import {CommonStyles} from '../shared/Constants';

export const styles = {
  fab: {
    flexDirection: 'column',
    height: 35,
    width: 35,
    borderRadius: 70,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: '#ffffff',
  },
  icnScanner: {color: '#a9a9a9', fontSize: 16},
  viewScanner: {
    flex: 0.3,
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    right: Platform.OS == 'android' ? 10 : 20,
    //marginTop: 5,
    //marginRight: 10,
  },
  iconSearch: {flex: 1, fontSize: 17, color: '#a9a9a9'},
  TextInputStyleClass: {
    flex: 2,
    //height: 18,
    underlineColor: 'transparent',
    //paddingRight: 90,
  },
  leftHeader: {
    flexDirection: 'column',
    height: 45,
    width: 45,
    borderRadius: 80,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: '#ffffff',
  },
  personBg: {
    flexDirection: 'column',
    height: 30,
    width: 30,
    borderRadius: 80,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: '#ffffff',
    borderColor: CommonStyles.appColor,
    borderWidth:1,
  },
  MainContainer: {
    position: 'relative',
    //top: 100,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'flex-end',
    flex: 1,
  },
  container: {
    flex: 1,
    backgroundColor: '#ffffff',
    borderTopLeftRadius: 35,
    borderTopRightRadius: 35,
  },
  modal: {
    margin: 0,
    backgroundColor: '#ffffff',
    height: 200,
    flex: 0,
    bottom: 0,
    position: 'absolute',
    width: '100%',
    borderTopLeftRadius: 35,
    borderTopRightRadius: 35,
  },
  mapStyle: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    flex: 1,
  },
  dbList: {
    borderColor: '#e0e0e0',
    width: Dimensions.get('window').width / 2.2,
    height: Dimensions.get('window').width / 1.8,
    borderBottomWidth: 1,
    borderRightWidth: 1,
    //borderRadius: 10,
    paddingLeft: 10,
    paddingRight: 10,
  },
  iconViewStyle: {
    // flex: 1,
    height: 35,
    width: 35,
    borderRadius: 70,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: '#ffffff',
    borderColor: CommonStyles.appColor,
    borderWidth: 2,
  },
  iconStyle: {
    color: CommonStyles.appColor,
    fontSize: 18,
  },
  invitationTextView: {
    flex: 0.5,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  userName: {
    color: '#000000',
    fontSize: 18,
  },
  profileCircleView: {
    flexDirection: 'row',
    flex: 0.7,
    alignSelf: 'center',
    position: 'relative',
  },
  nameTitleView: {
    flex: 0.3,
    flexDirection: 'column',
    //margin: 70,
    //width: Dimensions.get('window').width / 2.4,
    alignSelf: 'center',
  },
  touchableMessage: {
    //flex: 0.2,
    backgroundColor: CommonStyles.appColor,
    paddingVertical: 5,
    borderRadius: 35,
    alignItems: 'center',
    marginBottom: 12,
    marginLeft: 20,
    marginRight: 20,
  },
  headerCustomMenu: {
    marginRight: 5,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    borderRadius: 100,
  },
  headerTextMenu: {
    color: 'red',
  },
  headerCenterView: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: 'white',
    borderBottomLeftRadius: 40,
    borderBottomRightRadius: 40,
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    width: Dimensions.get('window').width * 0.56,
  },
};